<?php

declare(strict_types=1);

namespace App\Database\Seeds;

use App\Database\Seeds\Concerns\IdempotentSeederSupport;
use CodeIgniter\Database\Seeder;

/**
 * Creates the Components / Bloques page that showcases the starter site
 * structure and links to the public pages where each block family lives.
 *
 * The page is intentionally lightweight: it uses a visible container block to
 * demonstrate the generic wrapper primitive, then surfaces the existing demo
 * pages through a card grid so the whole starter remains easy to audit.
 */
class SiteComponentsPageSeeder extends Seeder
{
    use IdempotentSeederSupport;

    public function run(): void
    {
        $langIds = $this->langIds(['es', 'en', 'fr', 'pt']);
        if (! isset($langIds['es'], $langIds['en'])) {
            echo "SiteComponentsPageSeeder: missing languages. Seed CmsLanguageSeeder first.\n";
            return;
        }

        $pageId = $this->upsertPage();
        $this->upsertPageTranslation($pageId, $langIds['es'], [
            'slug'             => 'bloques',
            'title'            => 'Bloques y Componentes',
            'excerpt'          => 'Recorrido público por las piezas que el starter genera con sus seeders.',
            'meta_title'       => 'Bloques y Componentes | Mi Sitio',
            'meta_description' => 'Explora las páginas públicas que representan todos los bloques del starter.',
            'canonical_url'    => null,
            'robots'           => 'index, follow',
            'schema_data'      => null,
        ]);
        $this->upsertPageTranslation($pageId, $langIds['en'], [
            'slug'             => 'components',
            'title'            => 'Blocks and Components',
            'excerpt'          => 'Public walkthrough of the pieces generated by the starter seeders.',
            'meta_title'       => 'Blocks and Components | My Site',
            'meta_description' => 'Explore the public pages that represent every starter block.',
            'canonical_url'    => null,
            'robots'           => 'index, follow',
            'schema_data'      => null,
        ]);
        if (isset($langIds['fr'])) {
            $this->upsertPageTranslation($pageId, $langIds['fr'], [
                'slug'             => 'blocs',
                'title'            => 'Blocs et Composants',
                'excerpt'          => "Parcours public des éléments générés par les seeders du starter.",
                'meta_title'       => 'Blocs et Composants | Mon Site',
                'meta_description' => "Découvrez les pages publiques qui représentent tous les blocs du starter.",
                'canonical_url'    => null,
                'robots'           => 'index, follow',
                'schema_data'      => null,
            ]);
        }
        if (isset($langIds['pt'])) {
            $this->upsertPageTranslation($pageId, $langIds['pt'], [
                'slug'             => 'blocos',
                'title'            => 'Blocos e Componentes',
                'excerpt'          => 'Percurso público pelas peças que o starter gera com seus seeders.',
                'meta_title'       => 'Blocos e Componentes | Meu Site',
                'meta_description' => 'Explore as páginas públicas que representam todos os blocos do starter.',
                'canonical_url'    => null,
                'robots'           => 'index, follow',
                'schema_data'      => null,
            ]);
        }

        $this->resetPageBlocks($pageId);

        $blockIds = $this->blockIds([
            'page_header',
            'rich_text',
            'container',
            'cards_grid',
            'card_item',
            'cta',
        ]);

        $this->upsertBlock(
            $pageId,
            $blockIds,
            'page_header',
            1,
            ['bg_color' => 'bg-gray-100', 'css_class' => ''],
            [
                'es' => [
                    'heading'          => 'Bloques y Componentes',
                    'subheading'       => 'Cada bloque público del starter vive en una página real y navegable.',
                    'breadcrumb_label' => 'Inicio',
                    'breadcrumb_url'   => '/',
                ],
                'en' => [
                    'heading'          => 'Blocks and Components',
                    'subheading'       => 'Every public starter block lives on a real, navigable page.',
                    'breadcrumb_label' => 'Home',
                    'breadcrumb_url'   => '/',
                ],
                'fr' => [
                    'heading'          => 'Blocs et Composants',
                    'subheading'       => "Chaque bloc public du starter vit sur une page réelle et navigable.",
                    'breadcrumb_label' => 'Accueil',
                    'breadcrumb_url'   => '/',
                ],
                'pt' => [
                    'heading'          => 'Blocos e Componentes',
                    'subheading'       => 'Cada bloco público do starter vive em uma página real e navegável.',
                    'breadcrumb_label' => 'Início',
                    'breadcrumb_url'   => '/',
                ],
            ],
            $langIds
        );

        $this->upsertBlock(
            $pageId,
            $blockIds,
            'rich_text',
            2,
            ['css_class' => ''],
            [
                'es' => [
                    'content' => '<p>Este starter no depende de páginas ocultas ni de vistas obsoletas para mostrar sus bloques. El contenido de ejemplo se reparte en páginas públicas reales: inicio, quiénes somos, historia, portafolio, noticias, multimedia, contacto y esta página de bloques.</p><p>La idea es simple: si un bloque se crea por seeders, debe poder verse sin trabajo manual adicional. Así mantenemos el sistema auditable, consistente y fácil de mantener.</p>',
                ],
                'en' => [
                    'content' => '<p>This starter does not depend on hidden pages or obsolete views to showcase its blocks. The example content is distributed across real public pages: home, about, history, portfolio, news, multimedia, contact, and this blocks page.</p><p>The idea is simple: if a block is seeded, it should be visible without manual work. That keeps the system auditable, consistent, and easy to maintain.</p>',
                ],
                'fr' => [
                    'content' => "<p>Ce starter ne dépend pas de pages cachées ni de vues obsolètes pour présenter ses blocs. Le contenu d'exemple est réparti sur des pages publiques réelles : accueil, à propos, histoire, portefeuille, actualités, multimédia, contact et cette page de blocs.</p><p>L'idée est simple : si un bloc est généré par un seeder, il doit être visible sans travail manuel supplémentaire. Cela garde le système auditable, cohérent et facile à maintenir.</p>",
                ],
                'pt' => [
                    'content' => '<p>Este starter não depende de páginas ocultas nem de views obsoletas para exibir seus blocos. O conteúdo de exemplo é distribuído em páginas públicas reais: início, sobre nós, história, portfólio, notícias, multimídia, contato e esta página de blocos.</p><p>A ideia é simples: se um bloco é criado por seeders, ele deve poder ser visto sem trabalho manual adicional. Isso mantém o sistema auditável, consistente e fácil de manter.</p>',
                ],
            ],
            $langIds
        );

        $containerId = $this->upsertBlock(
            $pageId,
            $blockIds,
            'container',
            3,
            ['css_class' => 'not-prose my-12 rounded-3xl border border-slate-200 bg-slate-50/90 p-6 shadow-sm md:p-10'],
            ['es' => [], 'en' => []],
            $langIds
        );

        $cardsGridId = $this->upsertBlock(
            $pageId,
            $blockIds,
            'cards_grid',
            1,
            ['columns_desktop' => '3', 'variant' => 'bordered', 'css_class' => ''],
            ['es' => [], 'en' => []],
            $langIds,
            $containerId
        );

        $cards = [
            [
                'sort_order' => 1,
                'config'     => ['image' => $this->mediaReference('https://picsum.photos/id/1011/900/600')],
                'es' => [
                    'title'       => 'Inicio',
                    'description' => 'Carrusel hero, grilla de noticias y CTA principal.',
                    'link_label'  => 'Abrir inicio',
                    'link_url'    => '/es',
                ],
                'en' => [
                    'title'       => 'Home',
                    'description' => 'Hero slider, news grid, and the main CTA.',
                    'link_label'  => 'Open home',
                    'link_url'    => '/en',
                ],
                'fr' => [
                    'title'       => 'Accueil',
                    'description' => 'Carrousel principal, grille d\'actualités et CTA principal.',
                    'link_label'  => "Ouvrir l'accueil",
                    'link_url'    => '/fr',
                ],
                'pt' => [
                    'title'       => 'Início',
                    'description' => 'Carrossel hero, grade de notícias e CTA principal.',
                    'link_label'  => 'Abrir início',
                    'link_url'    => '/pt',
                ],
            ],
            [
                'sort_order' => 2,
                'config'     => ['image' => $this->mediaReference('https://picsum.photos/id/1015/900/600')],
                'es' => [
                    'title'       => 'Quiénes somos',
                    'description' => 'Hero banner, texto, cards, métricas, carrusel, galería y video.',
                    'link_label'  => 'Abrir página',
                    'link_url'    => '/es/nosotros',
                ],
                'en' => [
                    'title'       => 'About us',
                    'description' => 'Hero banner, text, cards, metrics, slider, gallery, and video.',
                    'link_label'  => 'Open page',
                    'link_url'    => '/en/about',
                ],
                'fr' => [
                    'title'       => 'À propos',
                    'description' => 'Bannière hero, texte, cartes, indicateurs, carrousel, galerie et vidéo.',
                    'link_label'  => 'Ouvrir la page',
                    'link_url'    => '/fr/a-propos',
                ],
                'pt' => [
                    'title'       => 'Quem somos',
                    'description' => 'Banner hero, texto, cards, métricas, carrossel, galeria e vídeo.',
                    'link_label'  => 'Abrir página',
                    'link_url'    => '/pt/sobre',
                ],
            ],
            [
                'sort_order' => 3,
                'config'     => ['image' => $this->mediaReference('https://picsum.photos/id/1035/900/600')],
                'es' => [
                    'title'       => 'Historia',
                    'description' => 'Métricas, acordeón, imagen y CTA editorial.',
                    'link_label'  => 'Ver historia',
                    'link_url'    => '/es/historia',
                ],
                'en' => [
                    'title'       => 'History',
                    'description' => 'Metrics, accordion, image, and editorial CTA.',
                    'link_label'  => 'View history',
                    'link_url'    => '/en/history',
                ],
                'fr' => [
                    'title'       => 'Histoire',
                    'description' => 'Indicateurs, accordéon, image et CTA éditorial.',
                    'link_label'  => "Voir l'histoire",
                    'link_url'    => '/fr/histoire',
                ],
                'pt' => [
                    'title'       => 'História',
                    'description' => 'Métricas, acordeão, imagem e CTA editorial.',
                    'link_label'  => 'Ver história',
                    'link_url'    => '/pt/historia',
                ],
            ],
            [
                'sort_order' => 4,
                'config'     => ['image' => $this->mediaReference('https://picsum.photos/id/1025/900/600')],
                'es' => [
                    'title'       => 'Portafolio',
                    'description' => 'Listado completo de colección, alertas, tabs e imágenes.',
                    'link_label'  => 'Abrir portafolio',
                    'link_url'    => '/es/portafolio',
                ],
                'en' => [
                    'title'       => 'Portfolio',
                    'description' => 'Full collection listing, alerts, tabs, and images.',
                    'link_label'  => 'Open portfolio',
                    'link_url'    => '/en/portfolio',
                ],
                'fr' => [
                    'title'       => 'Portefeuille',
                    'description' => "Liste complète de la collection, alertes, onglets et images.",
                    'link_label'  => 'Ouvrir le portefeuille',
                    'link_url'    => '/fr/portefeuille',
                ],
                'pt' => [
                    'title'       => 'Portfólio',
                    'description' => 'Listagem completa da coleção, alertas, abas e imagens.',
                    'link_label'  => 'Abrir portfólio',
                    'link_url'    => '/pt/portfolio',
                ],
            ],
            [
                'sort_order' => 5,
                'config'     => ['image' => $this->mediaReference('https://picsum.photos/id/1074/900/600')],
                'es' => [
                    'title'       => 'Multimedia',
                    'description' => 'Galerías con varias presentaciones, visor en línea y video incorporado.',
                    'link_label'  => 'Abrir multimedia',
                    'link_url'    => '/es/multimedia',
                ],
                'en' => [
                    'title'       => 'Media',
                    'description' => 'Galleries with multiple presentations, inline preview, and embedded video.',
                    'link_label'  => 'Open media',
                    'link_url'    => '/en/media',
                ],
                'fr' => [
                    'title'       => 'Multimédia',
                    'description' => "Galeries avec plusieurs présentations, aperçu intégré et vidéo intégrée.",
                    'link_label'  => 'Ouvrir le multimédia',
                    'link_url'    => '/fr/multimedia',
                ],
                'pt' => [
                    'title'       => 'Multimídia',
                    'description' => 'Galerias com várias apresentações, pré-visualização integrada e vídeo incorporado.',
                    'link_label'  => 'Abrir multimídia',
                    'link_url'    => '/pt/multimidia',
                ],
            ],
            [
                'sort_order' => 6,
                'config'     => ['image' => $this->mediaReference('https://picsum.photos/id/1060/900/600')],
                'es' => [
                    'title'       => 'Noticias',
                    'description' => 'Grid de colección con imagen principal y contenido resumido.',
                    'link_label'  => 'Ir a noticias',
                    'link_url'    => '/es/noticias',
                ],
                'en' => [
                    'title'       => 'News',
                    'description' => 'Collection grid with a featured image and summary content.',
                    'link_label'  => 'Go to news',
                    'link_url'    => '/en/news',
                ],
                'fr' => [
                    'title'       => 'Actualités',
                    'description' => "Grille de collection avec image principale et contenu résumé.",
                    'link_label'  => 'Aller aux actualités',
                    'link_url'    => '/fr/actualites',
                ],
                'pt' => [
                    'title'       => 'Notícias',
                    'description' => 'Grade de coleção com imagem principal e conteúdo resumido.',
                    'link_label'  => 'Ir para notícias',
                    'link_url'    => '/pt/noticias',
                ],
            ],
            [
                'sort_order' => 7,
                'config'     => ['image' => $this->mediaReference('https://picsum.photos/id/1048/900/600')],
                'es' => [
                    'title'       => 'Contacto',
                    'description' => 'Formulario, información de contacto, mapa y redes.',
                    'link_label'  => 'Ir a contacto',
                    'link_url'    => '/es/contacto',
                ],
                'en' => [
                    'title'       => 'Contact',
                    'description' => 'Form, contact details, map, and social links.',
                    'link_label'  => 'Go to contact',
                    'link_url'    => '/en/contact',
                ],
                'fr' => [
                    'title'       => 'Contact',
                    'description' => 'Formulaire, coordonnées, carte et réseaux sociaux.',
                    'link_label'  => 'Aller au contact',
                    'link_url'    => '/fr/contact',
                ],
                'pt' => [
                    'title'       => 'Contato',
                    'description' => 'Formulário, informações de contato, mapa e redes sociais.',
                    'link_label'  => 'Ir para contato',
                    'link_url'    => '/pt/contato',
                ],
            ],
        ];

        if ($cardsGridId > 0) {
            $this->seedChildBlocks($pageId, $cardsGridId, 'card_item', $cards, $blockIds, $langIds);
        }

        $this->upsertBlock(
            $pageId,
            $blockIds,
            'cta',
            4,
            ['variant' => 'blue', 'css_class' => ''],
            [
                'es' => [
                    'heading' => 'Ya viste la cobertura completa',
                    'text'    => 'Ahora puedes recorrer cada página demo y confirmar visualmente que los bloques seeders están representados en el sitio público.',
                    'label'   => 'Ir a inicio',
                    'url'     => '/es',
                ],
                'en' => [
                    'heading' => 'You have seen the full coverage',
                    'text'    => 'Now you can browse each demo page and visually confirm that the seeded blocks are represented on the public site.',
                    'label'   => 'Go to home',
                    'url'     => '/en',
                ],
                'fr' => [
                    'heading' => 'Vous avez vu la couverture complète',
                    'text'    => "Vous pouvez désormais parcourir chaque page de démonstration et vérifier visuellement que les blocs générés par les seeders sont bien représentés sur le site public.",
                    'label'   => "Aller à l'accueil",
                    'url'     => '/fr',
                ],
                'pt' => [
                    'heading' => 'Você já viu a cobertura completa',
                    'text'    => 'Agora você pode percorrer cada página demo e confirmar visualmente que os blocos gerados pelos seeders estão representados no site público.',
                    'label'   => 'Ir para início',
                    'url'     => '/pt',
                ],
            ],
            $langIds
        );
    }

    private function upsertPage(): int
    {
        $existing = $this->db->table('cms_pages')
            ->select('cms_pages.id')
            ->join('cms_page_translations', 'cms_page_translations.page_id = cms_pages.id')
            ->where('cms_pages.deleted_at IS NULL', null, false)
            ->whereIn('cms_page_translations.slug', ['bloques', 'components'])
            ->orderBy('cms_pages.id', 'ASC')
            ->get()
            ->getRowArray();

        if ($existing !== null) {
            $pageId = (int) $existing['id'];
            $updatePayload = [
                'page_type'          => 'generic',
                'status'             => 'published',
                'published_at'       => date('Y-m-d H:i:s'),
                'scheduled_at'       => null,
                'sort_order'         => 45,
                'sitemap_priority'   => '0.5',
                'sitemap_changefreq' => 'monthly',
                'is_in_sitemap'      => 1,
                'deleted_at'         => null,
            ];
            if ($this->db->fieldExists('updated_at', 'cms_pages')) {
                $updatePayload['updated_at'] = date('Y-m-d H:i:s');
            }

            $this->db->table('cms_pages')
                ->where('id', $pageId)
                ->update($updatePayload);

            return $pageId;
        }

        // Create a dedicated demo page instead of reusing the first generic row.
        // That keeps this seeder stable even when the starter already contains
        // other generic pages from the base site bootstrap.
        $pageId = $this->createRecord('cms_pages', [
                'page_type'          => 'generic',
            'status'             => 'published',
            'published_at'       => date('Y-m-d H:i:s'),
            'scheduled_at'       => null,
            'sort_order'         => 45,
            'sitemap_priority'   => '0.5',
            'sitemap_changefreq' => 'monthly',
            'is_in_sitemap'      => 1,
            'deleted_at'         => null,
        ]);

        if ($pageId === null) {
            throw new \RuntimeException('SiteComponentsPageSeeder: unable to seed components page.');
        }

        return $pageId;
    }

    /**
     * @param array<string, mixed> $translationData
     */
    private function upsertPageTranslation(int $pageId, int $languageId, array $translationData): void
    {
        $slug = (string) ($translationData['slug'] ?? '');
        if ($slug !== '') {
            $conflict = $this->db->table('cms_page_translations')
                ->where('language_id', $languageId)
                ->where('slug', $slug)
                ->get()
                ->getRowArray();
            if ($conflict !== null && (int) $conflict['page_id'] !== $pageId) {
                $this->db->table('cms_page_translations')
                    ->where('id', (int) $conflict['id'])
                    ->update(array_merge($translationData, [
                        'page_id'     => $pageId,
                        'language_id' => $languageId,
                        'updated_at'  => date('Y-m-d H:i:s'),
                    ]));

                return;
            }
        }

        $this->upsertRecord('cms_page_translations', [
            'page_id'     => $pageId,
            'language_id' => $languageId,
        ], $translationData);
    }

    /**
     * @param array<string, int>                  $blockIds
     * @param array<string, array<string, mixed>> $translations
     * @param array<string, int>                  $langIds
     */
    private function upsertBlock(
        int $pageId,
        array $blockIds,
        string $blockKey,
        int $sortOrder,
        array $config,
        array $translations,
        array $langIds,
        ?int $parentInstanceId = null
    ): int {
        $blockId = $blockIds[$blockKey] ?? null;
        if ($blockId === null) {
            echo "SiteComponentsPageSeeder: block type '{$blockKey}' not found — skipped.\n";
            return 0;
        }

        $instanceId = $this->upsertRecord('cms_block_instances', [
            'block_id'           => $blockId,
            'owner_type'         => 'page',
            'owner_id'           => $pageId,
            'parent_instance_id' => $parentInstanceId,
            'sort_order'         => $sortOrder,
        ], [
            'column_index' => null,
            'is_active'    => 1,
            'block_config'  => json_encode($config, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
        ]);

        foreach ($translations as $langCode => $data) {
            $langId = $langIds[$langCode] ?? null;
            if ($langId === null || ! is_array($data) || $data === []) {
                continue;
            }
            $this->upsertTranslation($instanceId, $langId, $data);
        }

        return $instanceId;
    }

    /**
     * @param array<int, array<string, mixed>> $items
     * @param array<string, int>               $blockIds
     * @param array<string, int>               $langIds
     */
    private function seedChildBlocks(int $pageId, int $parentInstanceId, string $blockKey, array $items, array $blockIds, array $langIds): void
    {
        $blockId = $blockIds[$blockKey] ?? null;
        if ($blockId === null) {
            return;
        }

        foreach ($items as $item) {
            $instanceId = $this->upsertRecord('cms_block_instances', [
                'block_id'           => $blockId,
                'owner_type'         => 'page',
                'owner_id'           => $pageId,
                'parent_instance_id' => $parentInstanceId,
                'sort_order'         => (int) $item['sort_order'],
            ], [
                'column_index' => null,
                'is_active'    => 1,
                'block_config'  => json_encode(
                    is_array($item['config'] ?? null) ? $item['config'] : [],
                    JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
                ),
            ]);

            if ($instanceId === null) {
                continue;
            }

            foreach (['es', 'en', 'fr', 'pt'] as $lang) {
                $langId = $langIds[$lang] ?? null;
                if ($langId === null || ! isset($item[$lang])) {
                    continue;
                }
                $this->upsertTranslation($instanceId, $langId, $item[$lang]);
            }
        }
    }

    /** @param array<string, mixed> $blockData */
    private function upsertTranslation(int $instanceId, int $languageId, array $blockData): void
    {
        $this->upsertRecord('cms_block_instance_translations', [
            'instance_id' => $instanceId,
            'language_id' => $languageId,
        ], [
            'block_data'   => json_encode($blockData, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            'is_published' => 1,
        ]);
    }

    /** @param string[] $keys @return array<string, int> */
    private function blockIds(array $keys): array
    {
        $rows = $this->db->table('cms_content_blocks')
            ->whereIn('block_key', $keys)
            ->get()
            ->getResultArray();

        $map = [];
        foreach ($rows as $row) {
            $map[$row['block_key']] = (int) $row['id'];
        }

        return $map;
    }

    /** @param string[] $codes @return array<string, int> */
    private function langIds(array $codes): array
    {
        $rows = $this->db->table('cms_languages')
            ->whereIn('code', $codes)
            ->get()
            ->getResultArray();

        $map = [];
        foreach ($rows as $row) {
            $map[$row['code']] = (int) $row['id'];
        }

        return $map;
    }
}
